### ISSUE TITLE
size

### ISSUE THREAD

**Issue by Ahmad913-code** [alexch33/super-video-downloader#11]
too much size off app

**Comment by alexch33** [comment]
This is because app using python and ffmpeg binary files, if you want to
decrease app's size you should move all youtube-dl staff from app to
server, as i know all on market using this approach, but main idea of this
app is doing all work on the client, also moving youtube-dl significantly
decrease power of app

пн, 28 окт. 2024 г., 09:35 Ahmad913-code ***@***.***>:
