### ISSUE TITLE
currently its not detecting videos on instagram and daily motion and many other sites 

### ISSUE THREAD

**Issue by AmmarZafar00054** [alexch33/super-video-downloader#8]
3 to 4 days ago its working but now it stop detecting videos on multiple sites can you plz guide me what the issue now

**Comment by alexch33** [comment]
same for me, i've investigated and find out that this is youtube-dl android specific issue,  this because youtube-dlp library last version needs python 3.9, but in library packed python 3.8, there is [workaround](https://github.com/yausername/youtubedl-android/issues/293#issuecomment-2325957984), as i understand on his repos exists fixed version of library

Also issue may be fixed by disabling youtube-dl update on start, removing ```updateYoutubeDL()``` method from ```DLApplication.kt``` and reinstalling app

I am going to implement this fix little bit latter, i don't have time right now

**Comment by alexch33** [comment]
for me ```youtubedl_replace``` [branch](https://github.com/alexch33/super-video-downloader/tree/youtubedl_replace) working now, can you test?

**Comment by alexch33** [comment]
[pull request](https://github.com/alexch33/super-video-downloader/pull/10)
